In [1]:
import numpy

numpy.random.seed(11)

In [2]:
import numpy

t = numpy.arange(0, 10, 0.1)
n = numpy.random.randn(len(t))
nse = numpy.convolve(n, numpy.exp(-t / 0.05)) * 0.1
nse = nse[: len(t)]
sig = numpy.sin(2 * numpy.pi * t) + nse

In [3]:
from cogent3.maths.period import dft

pwr, period = dft(sig)
print(period)
print(pwr)

[  2.           2.04081633   2.08333333   2.12765957   2.17391304
   2.22222222   2.27272727   2.3255814    2.38095238   2.43902439
   2.5          2.56410256   2.63157895   2.7027027    2.77777778
   2.85714286   2.94117647   3.03030303   3.125        3.22580645
   3.33333333   3.44827586   3.57142857   3.7037037    3.84615385
   4.           4.16666667   4.34782609   4.54545455   4.76190476
   5.           5.26315789   5.55555556   5.88235294   6.25
   6.66666667   7.14285714   7.69230769   8.33333333   9.09090909
  10.          11.11111111  12.5         14.28571429  16.66666667
  20.          25.          33.33333333  50.         100.        ]
[ 1.06015801+0.00000000e+00j  0.74686707-1.93971914e-02j
  0.36784793-2.66370366e-02j  0.04384413+2.86970840e-02j
  1.54473269-2.43777386e-02j  0.28522968-2.33602932e-01j
 -0.09908167-8.09083592e-01j -0.17082184-3.71376271e-02j
 -0.89062721+6.28548281e-01j  0.7963791 -3.10035336e-01j
 -0.01840271+7.80492960e-01j  0.88651578-2.41151331e-01j
 -0

In [4]:
pwr = abs(pwr)
max_pwr, max_period = sorted(zip(pwr, period))[-1]
print(max_pwr, max_period)

50.768593471914606 10.0


In [5]:
from cogent3.maths.period import auto_corr

pwr, period = auto_corr(sig)
print(period)
print(pwr)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]
[ 1.63366075e+01 -1.47309007e+01 -3.99310414e+01 -4.94779387e+01
 -4.02111589e+01 -1.59402206e+01  1.38935958e+01  3.78082033e+01
  4.67917301e+01  3.80558458e+01  1.50298023e+01 -1.31498874e+01
 -3.58750562e+01 -4.44274029e+01 -3.59442269e+01 -1.42494835e+01
  1.23571124e+01  3.37998464e+01  4.19246214e+01  3.40423905e+01
  1.37305496e+01 -1.13403096e+01 -3.11639561e+01 -3.90121298e+01
 -3.19165151e+01 -1.29071920e+01  1.03347404e+01  2.88866727e+01
  3.61923373e+01  2.95836846e+01  1.19272046e+01 -9.60842692e+00
 -2.70680982e+01 -3.36897636e+01 -2.74936245e+01 -1.12432553e+01
  8.85493706e+00  2.50657815e+01  3.12033008e+01  2.55562690e+01
  1.03888477e+01 -8.05790735e+00 -2.29155248e+01 -

In [6]:
max_pwr, max_period = sorted(zip(pwr, period))[-1]
print(max_pwr, max_period)

46.791730073275666 10


In [7]:
s = (
    "ATCGTTGGGACCGGTTCAAGTTTTGGAACTCGCAAGGGGTGAATGGTCTTCGTCTAACGCTGG"
    "GGAACCCTGAATCGTTGTAACGCTGGGGTCTTTAACCGTTCTAATTTAACGCTGGGGGGTTCT"
    "AATTTTTAACCGCGGAATTGCGTC"
)

In [8]:
from cogent3.maths.stats.period import SeqToSymbols

seq_to_symbols = SeqToSymbols(["AA", "TT", "AT"])
symbols = seq_to_symbols(s)
len(symbols) == len(s)
symbols

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [9]:
from cogent3.maths.period import ipdft

powers, periods = ipdft(symbols)
powers

array([3.22082108e-14, 4.00000000e+00, 9.48683298e+00, 6.74585634e+00,
       3.46410162e+00, 3.20674669e+00, 4.13171488e+00, 1.21157382e+00,
       5.24998151e+00, 8.17918725e+00, 8.83176087e+00, 6.68973168e+00,
       2.30390506e+00, 5.77601816e+00, 7.39581554e+00, 9.80089521e+00,
       1.28140014e+01, 5.59887450e+00, 4.59868328e+00, 8.51990117e+00,
       6.87861072e+00, 2.21002402e+00, 2.99221455e+00, 7.02839146e+00,
       9.56255506e+00, 1.06605556e+01, 1.06350498e+01, 9.87505455e+00,
       8.75521377e+00, 7.58223742e+00, 6.57383339e+00, 5.86043328e+00,
       5.48856222e+00, 5.41967659e+00, 5.54831380e+00, 5.74584888e+00,
       5.89930756e+00, 5.92786864e+00, 5.78419759e+00, 5.45019553e+00,
       4.93168494e+00, 4.25398249e+00, 3.46051662e+00, 2.62061706e+00,
       1.86912424e+00, 1.51346882e+00, 1.83960376e+00, 2.57129507e+00,
       3.40313085e+00, 4.21317980e+00, 4.95053395e+00, 5.58947522e+00,
       6.11597773e+00, 6.52293480e+00, 6.80798765e+00, 6.97227258e+00,
      

In [10]:
periods

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149])

In [11]:
from cogent3.maths.period import auto_corr, hybrid

powers, periods = auto_corr(symbols)
powers

array([11.,  9., 11.,  9.,  6.,  9.,  7.,  7.,  5.,  6., 11.,  9.,  9.,
        8., 10.,  9.,  4.,  7., 10., 12., 11.,  7.,  9.,  7.,  8.,  5.,
        8.,  9.,  4.,  7.,  7., 11.,  9., 10.,  8.,  7.,  6.,  5.,  5.,
        6.,  3.,  2.,  3.,  6.,  5.,  4.,  7.,  5.,  6.,  8.,  7.,  6.,
        4.,  8.,  5.,  5.,  4.,  5.,  7.,  6.,  3.,  4.,  5.,  5.,  4.,
        4.,  6.,  4.,  3.,  3.,  5.,  6.,  5.,  4.,  4.,  5.,  3.,  5.,
        5.,  5.,  3.,  2.,  5.,  6.,  6.,  6.,  6.,  6.,  4.,  3.,  3.,
        5.,  4.,  2.,  4.,  2.,  1.,  1.,  5.,  6.,  4.,  2.,  3.,  5.,
        5.,  5.,  6.,  5.,  5.,  3.,  3.,  3.,  2.,  2.,  3.,  2.,  1.,
        2.,  2.,  3.,  4.,  2.,  2.,  2.,  3.,  3.,  2.,  3.,  1.,  1.,
        0.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  0.,
        0.,  0.,  0.,  0.,  0.])

In [12]:
periods

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149])

In [13]:
powers, periods = hybrid(symbols)
powers

array([3.54290319e-13, 3.60000000e+01, 1.04355163e+02, 6.07127071e+01,
       2.07846097e+01, 2.88607202e+01, 2.89220041e+01, 8.48101672e+00,
       2.62499076e+01, 4.90751235e+01, 9.71493695e+01, 6.02075851e+01,
       2.07351455e+01, 4.62081453e+01, 7.39581554e+01, 8.82080569e+01,
       5.12560056e+01, 3.91921215e+01, 4.59868328e+01, 1.02238814e+02,
       7.56647179e+01, 1.54701681e+01, 2.69299309e+01, 4.91987402e+01,
       7.65004405e+01, 5.33027778e+01, 8.50803983e+01, 8.88754909e+01,
       3.50208551e+01, 5.30756620e+01, 4.60168337e+01, 6.44647661e+01,
       4.93970600e+01, 5.41967659e+01, 4.43865104e+01, 4.02209421e+01,
       3.53958454e+01, 2.96393432e+01, 2.89209880e+01, 3.27011732e+01,
       1.47950548e+01, 8.50796497e+00, 1.03815499e+01, 1.57237024e+01,
       9.34562120e+00, 6.05387527e+00, 1.28772263e+01, 1.28564753e+01,
       2.04187851e+01, 3.37054384e+01, 3.46537377e+01, 3.35368513e+01,
       2.44639109e+01, 5.21834784e+01, 3.40399383e+01, 3.48613629e+01,
      

In [14]:
periods

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149])

In [15]:
from cogent3.maths.period import goertzel

pwr = goertzel(sig, 10)
print(pwr)

50.76859347191462


In [16]:
powers, periods = auto_corr(symbols)
llim = 2
period5 = 5 - llim
periods[period5]

5

In [17]:
powers[period5]

9.0

In [18]:
from cogent3.maths.period import goertzel

period = 4
power = goertzel(symbols, period)
ipdft_powers, periods = ipdft(symbols)
ipdft_power = abs(ipdft_powers[period - llim])
round(power, 6) == round(ipdft_power, 6)
power

9.486832980505154

In [19]:
power = hybrid(symbols, period=period)
power

104.35516278555667

In [20]:
from cogent3.maths.period import Goertzel

goertzel_calc = Goertzel(len(sig), period=10)

In [21]:
from cogent3.maths.stats.period import blockwise_bootstrap

obs_stat, p = blockwise_bootstrap(
    sig, calc=goertzel_calc, block_size=10, num_reps=1000
)
print(obs_stat)
print(p)

50.76859347191462
0.0


In [22]:
from cogent3.maths.period import Hybrid

hybrid_calculator = Hybrid(len(s), period=4)

In [23]:
from cogent3.maths.stats.period import SeqToSymbols

seq_to_symbols = SeqToSymbols(["AA", "TT", "AT"], length=len(s))

In [24]:
from cogent3.maths.stats.period import blockwise_bootstrap

stat, p = blockwise_bootstrap(
    s,
    calc=hybrid_calculator,
    block_size=10,
    num_reps=1000,
    seq_to_symbols=seq_to_symbols,
)
print(stat)
p < 0.1

104.35516278555667


True